# Install miscellaneous packages that do no directly interact with
# any other larger system.
---
- name: Install miscellaneous packages on Fedora
  hosts: localhost
  tasks:
  - when: ansible_distribution == "Fedora"
    block:
    - name: Install packages with DNF
      become: true
      ansible.builtin.dnf:
        name:
        - chromium
        - fd-find
        - NetworkManager-tui
        - pavucontrol
        - playerctl
        - python3-devel
        - ripgrep
        - ShellCheck
        - systemd-devel
        - vim
        - wl-clipboard
        - htop
        state: latest
