# Install miscellaneous packages that do no directly interact with
# any other larger system.
---
- name: Install miscellaneous packages on Fedora
  hosts: localhost
  tasks:
  - when: ansible_distribution == "Fedora"
    block:
    - name: Install packages with DNF
      become: true
      ansible.builtin.dnf:
        name:
        - NetworkManager-tui
        - ShellCheck
        - chromium
        - fd-find
        - gnome-shell-extension-pop-shell
        - htop
        - pavucontrol
        - playerctl
        - python3-devel
        - ripgrep
        - systemd-devel
        - vim
        - wl-clipboard
        - xprop
        state: latest

    - name: Install gnome extension manager
      community.general.flatpak:
        name: com.mattjakeman.ExtensionManager
        state: latest
